version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appleboss-app
    volumes:
      - ./src:/var/www/html
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:80"
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appleboss-queue
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    command: php artisan queue:work --tries=3 --timeout=90

  db:
    image: postgres:15
    container_name: appleboss-db
    restart: always
    environment:
      POSTGRES_DB: appleboss
      POSTGRES_USER: user
      POSTGRES_PASSWORD: APPLEBOSSjulian2023
    volumes:
      - appleboss-laravel_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node:
    image: node:18
    container_name: appleboss-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: sh -c "npm install && npm run build"

  adminer:
    image: adminer
    container_name: appleboss-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  appleboss-laravel_db_data:
    external: true
