version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appleboss-app
    volumes:
      - ./src:/var/www/html:cached
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:80"
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appleboss-queue
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html:cached
      - ./src/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    command: php artisan queue:work --tries=3 --timeout=90

  db:
    image: postgres:15
    container_name: appleboss-db
    restart: always
    environment:
      POSTGRES_DB: appleboss
      POSTGRES_USER: user
      POSTGRES_PASSWORD: APPLEBOSSjulian2023
    volumes:
      - appleboss-laravel_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node:
    image: node:18
    container_name: appleboss-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - appleboss_node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  adminer:
    image: adminer
    container_name: appleboss-adminer
    restart: always
    ports:
      - "8080:8080"

  # ✅ NUEVO: n8n local
  n8n:
    image: n8nio/n8n:latest
    container_name: appleboss-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=superseguro

      - TZ=America/La_Paz
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http

    # 🔴 FIX PARA SAFARI / DEV
      - N8N_SECURE_COOKIE=false
    volumes:
      - appleboss_n8n_data:/home/node/.n8n

volumes:
  appleboss-laravel_db_data:
  appleboss_node_modules:
  appleboss_n8n_data:
