<?php

namespace App\Support\FichaTecnica;

/**
 * El nombre que ve la gente para cada característica de la ficha técnica.
 *
 * La tienda los toma de `resources/js/Components/Store/fichaTecnica.jsx`; el servidor los necesita para
 * escribir la misma ficha en texto (contenido legible sin JavaScript y llms.txt). Una prueba compara
 * las dos listas: si se agrega una característica allá, tiene que estar acá.
 */
class Etiquetas
{
    public const MAPA = [
        'acabado' => 'Acabado',
        'almacenamiento' => 'Almacenamiento',
        'ampliacion' => 'Ampliación',
        'ancho_banda' => 'Ancho de banda de memoria',
        'apple_intelligence' => 'Apple Intelligence',
        'asistente' => 'Asistente de voz',
        'audio' => 'Parlantes',
        'audio_espacial' => 'Audio Espacial',
        'autonomia' => 'Autonomía',
        'banda_ultraancha' => 'Banda ultraancha',
        'bateria' => 'Batería',
        'bateria_mah' => 'Capacidad de batería',
        'bateria_wh' => 'Batería',
        'biometria' => 'Desbloqueo',
        'bluetooth' => 'Bluetooth',
        'boton_accion' => 'Botón Acción',
        'brillo' => 'Brillo',
        'cable' => 'Cable',
        'camara' => 'Cámara',
        'camara_frontal' => 'Cámara frontal',
        'camara_principal' => 'Cámara principal',
        'camara_ultra' => 'Ultra gran angular',
        'cancelacion_ruido' => 'Cancelación de ruido',
        'capacidad' => 'Almacenamiento',
        'carga' => 'Carga rápida',
        'carga_inalambrica' => 'Carga inalámbrica',
        'carga_rapida' => 'Carga rápida',
        'cargador' => 'Cargador',
        'casa_inteligente' => 'Casa inteligente',
        'chip' => 'Chip',
        'ciclos_bateria' => 'Ciclos de carga',
        'coleccion' => 'Colección',
        'color' => 'Color',
        'compatibilidad' => 'Compatible con',
        'conectividad' => 'Conexión',
        'conectores' => 'Conectores',
        'contraste' => 'Contraste',
        'control' => 'Control',
        'control_camara' => 'Control de Cámara',
        'controles' => 'Controles',
        'cpu_cores' => 'CPU',
        'dimensiones' => 'Dimensiones',
        'dureza' => 'Dureza',
        'endurecido' => 'Cómo se endurece',
        'entrada' => 'Corriente',
        'estuche' => 'Estuche',
        'ethernet' => 'Ethernet',
        'fabricante' => 'Fabricante',
        'filtro' => 'Filtro',
        'funciones' => 'Funciones',
        'funciones_foto' => 'Funciones de foto',
        'funciones_pantalla' => 'Funciones de pantalla',
        'gatillos' => 'Gatillos adaptativos',
        'generacion' => 'Año',
        'gps' => 'Ubicación',
        'gpu' => 'Tarjeta gráfica',
        'gpu_cores' => 'GPU',
        'haptica' => 'Respuesta háptica',
        'iluminacion' => 'Luces',
        'instalacion' => 'Instalación',
        'juego' => 'Juego',
        'lanzamiento_so' => 'Salió con',
        'lapiz' => 'Apple Pencil compatible',
        'largo_cable' => 'Largo del cable',
        'lidar' => 'Escáner LiDAR',
        'magsafe' => 'MagSafe',
        'material' => 'Materiales',
        'memoria' => 'Memoria',
        'microfonos' => 'Micrófonos',
        'modelo' => 'Número de modelo',
        'modelo_compatible' => 'Compatible con',
        'neural_engine' => 'Neural Engine',
        'nfc' => 'NFC',
        'normas' => 'Normas de seguridad',
        'numero_serie' => 'Número de serie',
        'pantalla' => 'Tipo de pantalla',
        'pantalla_externa' => 'Pantalla externa',
        'pantallas_externas' => 'Monitores externos',
        'peso' => 'Peso',
        'potencia' => 'Potencia',
        'potencia_maxima' => 'Potencia máxima',
        'precision' => 'Precisión',
        'procesador' => 'Procesador',
        'proteccion' => 'Protección',
        'protocolos' => 'Tecnología de carga',
        'pruebas' => 'Pruebas independientes',
        'puerto' => 'Puerto',
        'puertos' => 'Puertos',
        'ram' => 'Memoria RAM',
        'recubrimiento' => 'Recubrimiento',
        'red' => 'Red móvil',
        'resistencia' => 'Resistencia al agua',
        'resolucion' => 'Resolución',
        'respuesta_tactil' => 'Respuesta táctil',
        'salidas' => 'Salidas',
        'salud' => 'Salud',
        'salud_auditiva' => 'Salud auditiva',
        'salud_bateria' => 'Salud de batería',
        'seguridad' => 'Seguridad',
        'sensores' => 'Sensores',
        'sim' => 'SIM',
        'sistema_camaras' => 'Cámaras traseras',
        'sistema_operativo' => 'Sistema operativo',
        'talla' => 'Talla de muñeca',
        'tamano_caja' => 'Tamaño de la caja',
        'tamano_pantalla' => 'Tamaño de pantalla',
        'tasa_refresco' => 'Frecuencia',
        'teclado' => 'Teclado',
        'teleobjetivo' => 'Teleobjetivo',
        'thread' => 'Thread',
        'tipo' => 'Tipo',
        'trackpad' => 'Trackpad',
        'traduccion' => 'Traducción en Vivo',
        'ultimo_ios' => 'Última versión de iOS',
        'ultimo_so' => 'Última versión de macOS',
        'video' => 'Grabación de video',
        'video_frontal' => 'Video frontal',
        'wifi' => 'Wi‑Fi',
        'zoom_optico' => 'Zoom óptico',
    ];

    public static function de(string $clave): string
    {
        return self::MAPA[$clave] ?? ucfirst(str_replace('_', ' ', $clave));
    }
}
